name: LearningOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: mkdir
      run: mkdir build_kernel
    - name: cd
      run: cd build_kernel
    - name: init submodule
      run: git submodule update --init
    - name: msbuild
      run: dotnet msbuild -v:n -p:OutputPath=./ -t:subproject
      
