#include "irq.hpp"

#include "method/irq0x00.cpp"
#include "method/irq0x01.cpp"
#include "method/irq0x02.cpp"
#include "method/irq0x03.cpp"
#include "method/irq0x04.cpp"
#include "method/irq0x05.cpp"
#include "method/irq0x06.cpp"
#include "method/irq0x07.cpp"
#include "method/irq0x08.cpp"
#include "method/irq0x09.cpp"
#include "method/irq0x0a.cpp"
#include "method/irq0x0b.cpp"
#include "method/irq0x0c.cpp"
#include "method/irq0x0d.cpp"
#include "method/irq0x0e.cpp"
#include "method/irq0x0f.cpp"
#include "method/irq0x10.cpp"
#include "method/irq0x11.cpp"
#include "method/irq0x12.cpp"
#include "method/irq0x13.cpp"
#include "method/irq0x14.cpp"
#include "method/irq0x15.cpp"
#include "method/irq0x16.cpp"
#include "method/irq0x17.cpp"
#include "method/irq0x18.cpp"
#include "method/irq0x19.cpp"
#include "method/irq0x1a.cpp"
#include "method/irq0x1b.cpp"
#include "method/irq0x1c.cpp"
#include "method/irq0x1d.cpp"
#include "method/irq0x1e.cpp"
#include "method/irq0x1f.cpp"
#include "method/irq0x20.cpp"
#include "method/irq0x21.cpp"
#include "method/irq0x22.cpp"
#include "method/irq0x23.cpp"
#include "method/irq0x24.cpp"
#include "method/irq0x25.cpp"
#include "method/irq0x26.cpp"
#include "method/irq0x27.cpp"
#include "method/irq0x28.cpp"
#include "method/irq0x29.cpp"
#include "method/irq0x2a.cpp"
#include "method/irq0x2b.cpp"
#include "method/irq0x2c.cpp"
#include "method/irq0x2d.cpp"
#include "method/irq0x2e.cpp"
#include "method/irq0x2f.cpp"

const system::interrupt::irq::IrqCall *system::interrupt::irq::irqs[0x30] = {
#define X(name) system::interrupt::irq::name,
    IrqList
#undef X
};
